# Generated by Django 5.2.4 on 2025-07-22 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_panel', '0002_alter_order_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_start_time', models.TimeField(default=datetime.time(9, 0), verbose_name='Xizmat boshlanish vaqti')),
                ('service_end_time', models.TimeField(default=datetime.time(23, 0), verbose_name='Xizmat tugash vaqti')),
                ('delivery_base_cost', models.DecimalField(decimal_places=2, default=10000, max_digits=10, verbose_name="Yetkazib berish boshlang'ich narxi (0-2km)")),
                ('delivery_cost_per_extra_km_block', models.DecimalField(decimal_places=2, default=5000, max_digits=10, verbose_name="Har 2km uchun qo'shimcha narx")),
                ('delivery_max_radius_km', models.FloatField(default=40.0, verbose_name='Maksimal yetkazib berish radiusi (km)')),
                ('broadcast_message_text', models.TextField(blank=True, null=True, verbose_name="E'lon matni")),
                ('last_broadcast_sent_at', models.DateTimeField(blank=True, null=True, verbose_name="Oxirgi e'lon yuborilgan vaqt")),
            ],
            options={
                'verbose_name': 'Bot Sozlamalari',
                'verbose_name_plural': 'Bot Sozlamalari',
            },
        ),
    ]
